if(EXISTS "/home/runner/work/olga_scheduler/olga_scheduler/_codeql_build_dir/test_olga_scheduler_capi[1]_tests.cmake")
  include("/home/runner/work/olga_scheduler/olga_scheduler/_codeql_build_dir/test_olga_scheduler_capi[1]_tests.cmake")
else()
  add_test(test_olga_scheduler_capi_NOT_BUILT test_olga_scheduler_capi_NOT_BUILT)
endif()
